# Generated by Django 5.2.8 on 2026-04-08 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0005_alter_productimage_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_image', to='heart.color')),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.productimage')),
            ],
        ),
    ]
