# Generated by Django 5.2.8 on 2026-04-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0006_primarycolorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarycolorimage',
            name='color',
        ),
        migrations.RemoveField(
            model_name='primarycolorimage',
            name='product_image',
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product', 'color'), name='unique_primary_per_color'),
        ),
        migrations.DeleteModel(
            name='PrimaryColorImage',
        ),
    ]
