# Generated by Django 5.2.8 on 2026-04-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0007_remove_primarycolorimage_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
