# Generated by Django 5.2.8 on 2026-04-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0008_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='approved', max_length=10),
        ),
    ]
