# Generated by Django 5.2.8 on 2026-06-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0010_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='code_promo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
