# Generated by Django 5.2.8 on 2026-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0011_cart_code_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='code_promo',
            field=models.CharField(default='no_code', max_length=100),
        ),
    ]
