# Generated by Django 5.2.8 on 2026-06-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0013_alter_cart_code_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
