# Generated by Django 5.2.8 on 2026-06-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0014_contact_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
