# Generated by Django 5.2.8 on 2026-06-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0015_contact_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
