# Generated by Django 5.2.8 on 2026-06-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0016_contact_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
